---
- hosts:      localhost
  connection: local
  vars:
    
    homebrew_installed_packages:
      - jq
      - node
      - yarn
      - zsh
      - zsh-completions

    homebrew_uninstalled_packages: []

    homebrew_cask_apps:
      - 1password
      - calibre
      - dash
      - dropbox
      - docker
      - evernote
      - firefox
      - google-chrome
      - google-drive-file-stream
      - imageoptim
      - iterm2
      - phpstorm
      - sequel-pro
      - skype
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager # 
      - virtualbox # | https://www.virtualbox.org/
      - vlc 

    zsh_path: /usr/local/bin/zsh

  roles:
    - cubicmushroom.homebrew


  tasks:

    ### ZSH radness 

    - name: Determine if zsh is default/current shell
      shell: echo ${SHELL}
      register: current_shell
      changed_when: false
      tags:
        - zsh

    - name: Enable zsh in /etc/shells
      shell: /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
      when: current_shell.stdout != '/usr/local/bin/zsh'    
      tags: 
        - zsh

    - name: Set zsh as default shell
      shell: chsh -s {{ zsh_path }}
      when: current_shell.stdout != '/usr/local/bin/zsh'
      register: chsh_output
      tags: 
        - zsh


    ### Projects

    - name: Directory Service API
      git:
        repo: git@gitlab.com:cubicmushroom/directory/directory-api
        dest: ${HOME}/src/gitlab.com/cubicmushroom/directory/directory-api
        key_file: ${HOME}/.ssh/id_rsa
        accept_hostkey: yes
        ssh_opts: -o StrictHostKeyChecking=no
      tags:
        - projects
        - projects:driectory

    - name: Directory Service font-end
      git:
        repo: git@gitlab.com:cubicmushroom/directory/react-front-end
        dest: ${HOME}/src/gitlab.com/cubicmushroom/directory/react-front-end
        key_file: ${HOME}/.ssh/id_rsa
        accept_hostkey: yes
        ssh_opts: -o StrictHostKeyChecking=no
      tags:
        - projects
        - projects:driectory
