---
- hosts:      localhost
  connection: local
  vars:
    
    repo_path: ~/.my-mac

    homebrew_installed_packages:
      - jq
      - node
      - tmux
      - yarn
      - zsh
      - zsh-completions

    homebrew_uninstalled_packages: []

    homebrew_cask_apps:
      - 1password
      - calibre
      - dash
      - dropbox
      - docker
      - evernote
      - firefox
      - google-chrome
      - google-drive-file-stream
      - imageoptim
      - iterm2
      - phpstorm
      - postman
      - sequel-pro
      - skype
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager # 
      - virtualbox # | https://www.virtualbox.org/
      - vlc 

    zsh_path: /usr/local/bin/zsh

  roles:
    - cubicmushroom.homebrew


  tasks:

    ### ZSH radness 

    - name: Determine if zsh is default/current shell
      shell: echo ${SHELL}
      register: current_shell
      changed_when: false
      tags:
        - zsh

    - name: Enable zsh in /etc/shells
      shell: /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
      when: current_shell.stdout != '/usr/local/bin/zsh'    
      tags: 
        - zsh

    - name: Set zsh as default shell
      shell: chsh -s {{ zsh_path }}
      when: current_shell.stdout != '/usr/local/bin/zsh'
      register: chsh_output
      tags: 
        - zsh

    - name: Symlink .zshrc
      file:
        state: link
        src: "{{ repo_path }}/dotfiles/.zshrc"
        dest: ${HOME}/.zshrc
      tags:
        - zsh

    ### Oh my Zsh

    - name: Check if oh-my-zsh is installed
      stat:
        path: ${HOME}/.oh-my-zsh
      register: omz_check
      tags:
        - zsh
        - oh-my-zsh

    - name: Install oh-my-zsh
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
      when: omz_check.stat.exists == false
      tags:
        - zsh
        - oh-my-zsh

    ### Desktop & workpaces

    - name: Don’t automatically rearrange Spaces based on most recent use
      osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: false
        state: present
      tags:
        - osx
        - desktop
        - workspaces


    ### Keyboard tweaks

    - name: Enable F keys without need for Fn key
      osx_defaults:
        domain: Apple Global Domain
        key: com.apple.keyboard.fnState
        type: bool
        value: true
        state: present
      tags:
        - osx
        - keyboard


    ### Mouse/Trackpad tweaks

    - name: Enable tap to click for mightymouse
      osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        key: Clicking
        state: present
        type: int
        value: 1
      tags:
        - osx
        - mouse

    - name: Enable tap to click for trackpad
      osx_defaults:
        domain: NSGlobalDomain
        host: currentHost
        key: com.apple.mouse.tapBehavior
        state: present
        type: int
        value: 1
      tags:
        - osx
        - trackpad

    - name: Enable tap to click o boot screen
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.mouse.tapBehavior
        state: present
        type: int
        value: 1
      tags:
        - osx
        - trackpad


    ### Projects

    - name: Directory Service API
      git:
        repo: git@gitlab.com:cubicmushroom/directory/directory-api
        dest: ${HOME}/src/gitlab.com/cubicmushroom/directory/directory-api
        key_file: ${HOME}/.ssh/id_rsa
        accept_hostkey: yes
        ssh_opts: -o StrictHostKeyChecking=no
      tags:
        - projects
        - projects:driectory

    - name: Directory Service font-end
      git:
        repo: git@gitlab.com:cubicmushroom/directory/react-front-end
        dest: ${HOME}/src/gitlab.com/cubicmushroom/directory/react-front-end
        key_file: ${HOME}/.ssh/id_rsa
        accept_hostkey: yes
        ssh_opts: -o StrictHostKeyChecking=no
      tags:
        - projects
        - projects:driectory
